"""Add password field to user model

Revision ID: 64587907cbc0
Revises: 1c77fb720133
Create Date: 2025-11-19 00:01:15.219555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64587907cbc0'
down_revision = '1c77fb720133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
